### ISSUE TITLE
Snap SDK did not return "status_code"

### ISSUE THREAD

**Issue by haritsfahreza** [veritrans/go-midtrans#18]
Hi @rizdaprasetya and Midtrans team,

As we know, `SnapResponse` struct has field `status_code` to keep HTTP Status Code from Midtrans. But I found that field is always empty and found that it does not use or set by any function right now. I need that field so I can check the error that happen on Midtrans API.

I will submit a PR regarding to this issue 😄 

Thanks!

**Comment by rizdaprasetya** [comment]
Already merged, Thanks again for contributing! :)
