### ISSUE TITLE
Refund support?

### ISSUE THREAD

**Issue by shcode** [veritrans/go-midtrans#46]
The core gateway doesn't include API for `refund` and `direct refund`

**Comment by mychaelgo** [comment]
@shcode i don't think so current version is support for `refund`. But contributing to this repo are welome 👍

**Comment by rizdaprasetya** [comment]
Yes for now it haven't been implemented.
Our team are currently developing further on this library, but haven't publish it yet. In the mean time contribution are welcome.

**Comment by rizdaprasetya** [comment]
Merged and fixed by https://github.com/veritrans/go-midtrans/pull/48
