### ISSUE TITLE
Wrong status_code on Response struct for CoreGateway

### ISSUE THREAD

**Issue by fajrifernanda** [veritrans/go-midtrans#49]
Hi midtrans team,
Based on this fix #19 , it fill the status_code both in SnapResponse's struct and Response's struct with http statuscode. 

But in CoreGateway, when getting status of an order `https://api.sandbox.midtrans.com/v2/some-order-id/status`, it gives the status_code result in response body based on transaction's status like image below.
<img width="269" alt="Screen Shot 2019-11-26 at 21 16 41" src="https://user-images.githubusercontent.com/26200571/69641307-8de3af00-1092-11ea-8a68-9fe9791f97a1.png">

Because of fix in #19 it will replace the status_code=407 (which explain the transaction's status) with status_code=200 from http status_code in Response of CoreGateway.

so the status_code in Response struct must not replaced with the http status code, because it is refer from transaction's status.

**Comment by rizdaprasetya** [comment]
Agree, that's unexpected behaviour. Will review your pull request.
thanks

**Comment by rizdaprasetya** [comment]
Merged fix https://github.com/veritrans/go-midtrans/pull/50
