### ISSUE TITLE
No documentation about set custom transaction expired

### ISSUE THREAD

**Issue by muhammadisa** [veritrans/go-midtrans#76]
Hello I am using midtrans for my business, and I have struggle finding how to define custom trx expire in ChargeReq.

I have try this one by reading the code of go-midtrans but this is not work, please help me by explain how to define custom
transaction expire in ChargeReq
```golang
req := &midtrans.ChargeReq{
		PaymentType: midtrans.SourceEchannel,
		MandiriBillBankTransferDetail: &midtrans.MandiriBillBankTransferDetail{
			BillInfo1: "complete payment",
			BillInfo2: "dept",
		},
                // how to set valid configuration for custom trx expire
		CustomExpiry: &midtrans.CustomExpiry{
			OrderTime:      trxTime.Format("2006-01-02 15:04:05 +0700"),
			ExpiryDuration: 1,
			Unit:           "HOUR",
		},
		TransactionDetails: midtrans.TransactionDetails{
			OrderID:  trxID,
			GrossAmt: grossAmt,
		},
		CustomerDetail: &midtrans.CustDetail{
			Phone: custPhone,
			FName: custName,
		},
		Items: &[]midtrans.ItemDetail{
			{
				ID:    itemID,
				Price: grossAmt,
				Qty:   1,
				Name:  itemName,
			},
		},
	}
```

**Comment by omarxp** [comment]
Hi @muhammadisa Thank you for reaching out to us.
could you elaborate on this => **but this is not work**, return an error or what? the code looks good.

note for CustomExpiry:
almost all value in the **OrderTime** are equal to transaction time, you can remove this field

thank you

**Comment by muhammadisa** [comment]
Hi @omarxp the last I tried using HOUR unit is not work, and the result in midtrans dashboard looks not same with the custom expiry that I set, but when I changed the unit to MINUTE and set ExpiryDuration to 120, its works maybe there is an logic error, but using MINUTE unit its work for me.

```golang
CustomExpiry: &midtrans.CustomExpiry{
	OrderTime:      trxTime.Format("2006-01-02 15:04:05 +0700"),
	ExpiryDuration: 120,
	Unit:           "MINUTE",
},
```
