### ISSUE TITLE
go-midtrans doesn't work while running inside docker container

### ISSUE THREAD

**Issue by muhammadisa** [veritrans/go-midtrans#77]
I found something weird while working with this go package, I tried to run it from Docker Container and I got error `One or more parameters in the payload is invalid.` but when I try it in localhost from my machine, it's working like a charm

Error Log from Docker Container
```
2021/01/02 20:41:46 Request  POST :  api.sandbox.midtrans.com /v2/charge
2021/01/02 20:41:46 One or more parameters in the payload is invalid.
```

Success Log from my local machine
```
2021/01/03 03:28:06 Request  POST :  api.sandbox.midtrans.com /v2/charge
2021/01/03 03:28:06 OK, Mandiri Bill transaction is successful
```

If there is a special configuration for run midtrans inside Docker
please add it into documentation thanks

**Comment by rizdaprasetya** [comment]
Hi @muhammadisa can you please share the log of what was your input/parameter when the issue happen?
Most likely some of your input param is empty/missing. 

When 2 kind of environment (localmachine vs docker) produce 2 different result (success vs failure), it usually happen if some ENV variable (or config files) at your docker is mistakenly empty/missing/not loaded.
thanks

**Comment by muhammadisa** [comment]
Hi @rizdaprasetya thanks for your response, looks like the error is on me, because I hard coded the midtrans secret key in my repo and I though git guardian delete it from my repo, so I move it into environment file and its work, thanks a lot.
